services:
  - docker

install:
  - docker build -t osrm-backend-k8s ./1.4
  - docker run -d -p 5000:5000 -e OSRM_PBF_URL='http://download.geofabrik.de/asia/maldives-latest.osm.pbf' --name osrm-backend osrm-backend-k8s

before_script:
  - npm install newman --global

script:
  - docker ps | grep -q osrm-backend-k8s
  - newman run tests/osrm_backend.postman_collection.json
  